# Generated by Django 4.1.3 on 2022-11-25 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_category", models.CharField(max_length=254, verbose_name="Nom")),
                ("image_category_url", models.TextField(verbose_name="imagelink")),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_organization",
                    models.CharField(max_length=254, verbose_name="Nom"),
                ),
                ("image_organization_url", models.TextField(verbose_name="imagelink")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_product", models.CharField(max_length=254, verbose_name="Nom")),
                ("image_product_url", models.TextField(verbose_name="imagelink")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_removed",
                    models.BooleanField(default=False, verbose_name="Removed"),
                ),
                (
                    "qty_total",
                    models.IntegerField(default=1, verbose_name="Total quantity"),
                ),
                (
                    "qty_available",
                    models.BooleanField(default=1, verbose_name="Total quantity"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
    ]
