# Generated by Django 4.1.3 on 2022-11-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="qty_available",
            field=models.IntegerField(default=1, verbose_name="Available quantity"),
        ),
    ]
