# Generated by Django 4.1.3 on 2022-11-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_product_qty_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_consumable",
            field=models.BooleanField(default=False, verbose_name="Consumable"),
        ),
    ]
