# Generated by Django 4.1.3 on 2022-11-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0002_reservation_product_rented_alter_reservation_renter"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="quantity_rented",
            field=models.IntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
