# Generated by Django 4.1.3 on 2022-11-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_reservation_quantity_rented"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_reservation_executed",
            field=models.BooleanField(default=False, verbose_name="Is executed"),
        ),
    ]
