# Generated by Django 4.1.3 on 2022-11-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_reservation_is_reservation_executed"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_endof_reservation_executed",
            field=models.BooleanField(
                default=False, verbose_name="End of reservation executed"
            ),
        ),
    ]
